### ISSUE TITLE
Add scoop

### ISSUE THREAD

**Issue by viceice** [renovatebot/docker-buildpack#83]
needed for new scoop package manager

ref renovatebot/renovate#7876 #77

**Comment by viceice** [comment]
@JamieMagee Now the hard part ? 🙃

**Comment by JamieMagee** [comment]
How hard can it be? I already added scoop support to Ansible :wink:  ansible-collections/community.windows#92

**Comment by JamieMagee** [comment]
Quite hard, as it turns out :facepalm: 

It looks like scoop doesn't completely support Linux. There are a couple of repos (https://github.com/ScoopInstaller/Excavator & https://github.com/Ash258/Scoop-GithubActions) which support _some_ parts of scoop (the auto-updater).

I've put what I have done in a branch, so you can take a look, and we can move forward if Linux support progresses. Until then, we should monitor https://github.com/lukesampson/scoop/issues/2137

**Comment by viceice** [comment]
I think we only need the auto-updater to fixup the buckets. if i remember correctly you can pass a single bucket file to be updated.

so we will need to get  [checkver](https://github.com/lukesampson/scoop/blob/master/bin/checkver.ps1) working, so we can run 

```pwsh
.\bin\checkver.ps1 node-lts -Update -Version 14.15.1
```

**Comment by JamieMagee** [comment]
Okay, I'll experiment with running these two scripts.

**Comment by viceice** [comment]
Duplicate of containerbase/buildpack#25
